# Digital Invest
version: '3'
services:

  digital-db:
    image: mongo
    container_name: digital-db
    ports:
      - 27017:27017
    volumes:
      - digital-invest-db:/data/db
      - ./assets/backups:/data/dump
    networks:
      - digital-invest-network

  digital-robo:
    build:
      context: .
      dockerfile: Dockerfile.Robo
    image: digital-robo:latest
    container_name: digital-robo
    depends_on:
      - digital-db
    links:
      - digital-db
    restart: always
    networks:
      - digital-invest-network

  digital-api:
    build:
      context: .
      dockerfile: Dockerfile.API
    image: digital-api:latest
    container_name: digital-api
    environment:
      ENV_PROFILE: Production
    ports:
      - 5000:5000
    depends_on:
      - digital-db
    links:
      - digital-db
    restart: always
    networks:
      - digital-invest-network

networks:
  digital-invest-network:
    driver: bridge

volumes:
  digital-invest-db: null
