//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital.assets.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("digital.assets.Texts.ErrorText", typeof(ErrorText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status do pedido deve estar em aberto.
        /// </summary>
        public static string CancelamentoSomenteStatusAberto {
            get {
                return ResourceManager.GetString("CancelamentoSomenteStatusAberto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não pode ser igual a anterior.
        /// </summary>
        public static string ConfirmacaoSenha {
            get {
                return ResourceManager.GetString("ConfirmacaoSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotações não encontradas.
        /// </summary>
        public static string CotacoesNaoExiste {
            get {
                return ResourceManager.GetString("CotacoesNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Numero CPF é Invalido.
        /// </summary>
        public static string CPFInvalido {
            get {
                return ResourceManager.GetString("CPFInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email e/ou CPF já cadastrados!.
        /// </summary>
        public static string EmailCPFJaCadastrado {
            get {
                return ResourceManager.GetString("EmailCPFJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este email não é válido.
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email é obrigatório.
        /// </summary>
        public static string EmailVazio {
            get {
                return ResourceManager.GetString("EmailVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado, informe o ERROR_ID para o administrador.
        /// </summary>
        public static string ErroServidor {
            get {
                return ResourceManager.GetString("ErroServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historico da carteira não encontrado.
        /// </summary>
        public static string HistoricoCarteiraNaoExiste {
            get {
                return ResourceManager.GetString("HistoricoCarteiraNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O horário da compra é de no mínimo, 2 horas acima do horário atual.
        /// </summary>
        public static string HoraCompraMinima {
            get {
                return ResourceManager.GetString("HoraCompraMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Id da Moeda é Obrigatória.
        /// </summary>
        public static string MoedaIdObrigatorio {
            get {
                return ResourceManager.GetString("MoedaIdObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeda(s) não encontrada(s).
        /// </summary>
        public static string MoedasNaoExiste {
            get {
                return ResourceManager.GetString("MoedasNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro, a quantidade do pedido não pode ser maior que o valor em carteira.
        /// </summary>
        public static string NovoPedidoMaiorCarteira {
            get {
                return ResourceManager.GetString("NovoPedidoMaiorCarteira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro nas cotações, nem todas as moedas tem cotações registradas.
        /// </summary>
        public static string NovoPedidoMoedaNaoEncontrada {
            get {
                return ResourceManager.GetString("NovoPedidoMoedaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido não encontrado.
        /// </summary>
        public static string PedidoNaoEncontrado {
            get {
                return ResourceManager.GetString("PedidoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedidos de venda não foram encontrados.
        /// </summary>
        public static string PedidosNaoEncontrados {
            get {
                return ResourceManager.GetString("PedidosNaoEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário ter moedas para compra.
        /// </summary>
        public static string QuantidadeMoedaCompra {
            get {
                return ResourceManager.GetString("QuantidadeMoedaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário informar quantas moedas deseja comprar.
        /// </summary>
        public static string QuantidadeMoedasMinima {
            get {
                return ResourceManager.GetString("QuantidadeMoedasMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha está vazia ou contem caracteres inválidos.
        /// </summary>
        public static string SenhaInvalida {
            get {
                return ResourceManager.GetString("SenhaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha antiga não pode ser igual a nova.
        /// </summary>
        public static string SenhasIguais {
            get {
                return ResourceManager.GetString("SenhasIguais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario ou senha incorretos.
        /// </summary>
        public static string UsuarioNaoExiste {
            get {
                return ResourceManager.GetString("UsuarioNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha precisa de no mínimo 6 caracteres.
        /// </summary>
        public static string ValorMinimoSenhaInvalido {
            get {
                return ResourceManager.GetString("ValorMinimoSenhaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor total da compra precisa ser superior a zero.
        /// </summary>
        public static string ValorTotalEMenorQueZero {
            get {
                return ResourceManager.GetString("ValorTotalEMenorQueZero", resourceCulture);
            }
        }
    }
}
