//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital.assets.Texts {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorText() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("digital.assets.Texts.ErrorText", typeof(ErrorText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha não pode ser igual a anterior.
        /// </summary>
        public static string ConfirmacaoSenha {
            get {
                return ResourceManager.GetString("ConfirmacaoSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cotações não encontradas.
        /// </summary>
        public static string CotacoesNaoExiste {
            get {
                return ResourceManager.GetString("CotacoesNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Numero CPF é Invalido.
        /// </summary>
        public static string CPFInvalido {
            get {
                return ResourceManager.GetString("CPFInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email e/ou CPF já cadastrados!.
        /// </summary>
        public static string EmailCPFJaCadastrado {
            get {
                return ResourceManager.GetString("EmailCPFJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este email não é válido.
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O email é obrigatório.
        /// </summary>
        public static string EmailVazio {
            get {
                return ResourceManager.GetString("EmailVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro inesperado, informe o ERROR_ID para o administrador.
        /// </summary>
        public static string ErroServidor {
            get {
                return ResourceManager.GetString("ErroServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O horário da compra é de no mínimo, 3 horas acima do horário atual.
        /// </summary>
        public static string HoraCompraMinima {
            get {
                return ResourceManager.GetString("HoraCompraMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Id da Moeda é Obrigatória.
        /// </summary>
        public static string MoedaIdObrigatorio {
            get {
                return ResourceManager.GetString("MoedaIdObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Moeda(s) não encontrada(s).
        /// </summary>
        public static string MoedasNaoExiste {
            get {
                return ResourceManager.GetString("MoedasNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro, a quantidade do pedido não pode ser maior que o valor em carteira.
        /// </summary>
        public static string NovoPedidoMaiorCarteira {
            get {
                return ResourceManager.GetString("NovoPedidoMaiorCarteira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro nas cotações, nem todas as moedas tem cotações registradas.
        /// </summary>
        public static string NovoPedidoMoedaNaoEncontrada {
            get {
                return ResourceManager.GetString("NovoPedidoMoedaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar quantas moedas deseja comprar.
        /// </summary>
        public static string QuantidadeMoedasMinima {
            get {
                return ResourceManager.GetString("QuantidadeMoedasMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha está vazia ou contem caracteres inválidos.
        /// </summary>
        public static string SenhaInvalida {
            get {
                return ResourceManager.GetString("SenhaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha antiga não pode ser igual a nova.
        /// </summary>
        public static string SenhasIguais {
            get {
                return ResourceManager.GetString("SenhasIguais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario ou senha incorretos.
        /// </summary>
        public static string UsuarioNaoExiste {
            get {
                return ResourceManager.GetString("UsuarioNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor total da compra precisa ser superior a zero.
        /// </summary>
        public static string ValorTotalEMenorQueZero {
            get {
                return ResourceManager.GetString("ValorTotalEMenorQueZero", resourceCulture);
            }
        }
    }
}
